export const flagsConfig = [
  { code: "AF", name: "Afghanistan", image: "js/games/flags/images/AF.png" },
  { code: "AL", name: "Albania", image: "js/games/flags/images/AL.png" },
  { code: "DZ", name: "Algeria", image: "js/games/flags/images/DZ.png" },
  { code: "AS", name: "American Samoa", image: "js/games/flags/images/AS.png" },
  { code: "AD", name: "Andorra", image: "js/games/flags/images/AD.png" },
  { code: "AO", name: "Angola", image: "js/games/flags/images/AO.png" },
  { code: "AI", name: "Anguilla", image: "js/games/flags/images/AI.png" },
  { code: "AQ", name: "Antarctica", image: "js/games/flags/images/AQ.png" },
  { code: "AG", name: "Antigua and Barbuda", image: "js/games/flags/images/AG.png" },
  { code: "AR", name: "Argentina", image: "js/games/flags/images/AR.png" },
  { code: "AM", name: "Armenia", image: "js/games/flags/images/AM.png" },
  { code: "AW", name: "Aruba", image: "js/games/flags/images/AW.png" },
  { code: "AU", name: "Australia", image: "js/games/flags/images/AU.png" },
  { code: "AT", name: "Austria", image: "js/games/flags/images/AT.png" },
  { code: "AZ", name: "Azerbaijan", image: "js/games/flags/images/AZ.png" },
  { code: "BS", name: "Bahamas", image: "js/games/flags/images/BS.png" },
  { code: "BH", name: "Bahrain", image: "js/games/flags/images/BH.png" },
  { code: "BD", name: "Bangladesh", image: "js/games/flags/images/BD.png" },
  { code: "BB", name: "Barbados", image: "js/games/flags/images/BB.png" },
  { code: "BY", name: "Belarus", image: "js/games/flags/images/BY.png" },
  { code: "BE", name: "Belgium", image: "js/games/flags/images/BE.png" },
  { code: "BZ", name: "Belize", image: "js/games/flags/images/BZ.png" },
  { code: "BJ", name: "Benin", image: "js/games/flags/images/BJ.png" },
  { code: "BM", name: "Bermuda", image: "js/games/flags/images/BM.png" },
  { code: "BT", name: "Bhutan", image: "js/games/flags/images/BT.png" },
  { code: "BO", name: "Bolivia", image: "js/games/flags/images/BO.png" },
  { code: "BA", name: "Bosnia and Herzegovina", image: "js/games/flags/images/BA.png" },
  { code: "BW", name: "Botswana", image: "js/games/flags/images/BW.png" },
  { code: "BR", name: "Brazil", image: "js/games/flags/images/BR.png" },
  { code: "IO", name: "British Indian Ocean Territory", image: "js/games/flags/images/IO.png" },
  { code: "BN", name: "Brunei", image: "js/games/flags/images/BN.png" },
  { code: "BG", name: "Bulgaria", image: "js/games/flags/images/BG.png" },
  { code: "BF", name: "Burkina Faso", image: "js/games/flags/images/BF.png" },
  { code: "BI", name: "Burundi", image: "js/games/flags/images/BI.png" },
  { code: "CV", name: "Cabo Verde", image: "js/games/flags/images/CV.png" },
  { code: "KH", name: "Cambodia", image: "js/games/flags/images/KH.png" },
  { code: "CM", name: "Cameroon", image: "js/games/flags/images/CM.png" },
  { code: "CA", name: "Canada", image: "js/games/flags/images/CA.png" },
  { code: "KY", name: "Cayman Islands", image: "js/games/flags/images/KY.png" },
  { code: "CF", name: "Central African Republic", image: "js/games/flags/images/CF.png" },
  { code: "TD", name: "Chad", image: "js/games/flags/images/TD.png" },
  { code: "CL", name: "Chile", image: "js/games/flags/images/CL.png" },
  { code: "CN", name: "China", image: "js/games/flags/images/CN.png" },
  { code: "CX", name: "Christmas Island", image: "js/games/flags/images/CX.png" },
  { code: "CC", name: "Cocos (Keeling) Islands", image: "js/games/flags/images/CC.png" },
  { code: "CO", name: "Colombia", image: "js/games/flags/images/CO.png" },
  { code: "KM", name: "Comoros", image: "js/games/flags/images/KM.png" },
  { code: "CG", name: "Congo Republic", image: "js/games/flags/images/CG.png" },
  { code: "CD", name: "Congo (DRC)", image: "js/games/flags/images/CD.png" },
  { code: "CK", name: "Cook Islands", image: "js/games/flags/images/CK.png" },
  { code: "CR", name: "Costa Rica", image: "js/games/flags/images/CR.png" },
  { code: "CI", name: "Côte d'Ivoire", image: "js/games/flags/images/CI.png" },
  { code: "HR", name: "Croatia", image: "js/games/flags/images/HR.png" },
  { code: "CU", name: "Cuba", image: "js/games/flags/images/CU.png" },
  { code: "CY", name: "Cyprus", image: "js/games/flags/images/CY.png" },
  { code: "CZ", name: "Czech Republic", image: "js/games/flags/images/CZ.png" },
  { code: "DK", name: "Denmark", image: "js/games/flags/images/DK.png" },
  { code: "DJ", name: "Djibouti", image: "js/games/flags/images/DJ.png" },
  { code: "DM", name: "Dominica", image: "js/games/flags/images/DM.png" },
  { code: "DO", name: "Dominican Republic", image: "js/games/flags/images/DO.png" },
  { code: "EC", name: "Ecuador", image: "js/games/flags/images/EC.png" },
  { code: "EG", name: "Egypt", image: "js/games/flags/images/EG.png" },
  { code: "SV", name: "El Salvador", image: "js/games/flags/images/SV.png" },
  { code: "GQ", name: "Equatorial Guinea", image: "js/games/flags/images/GQ.png" },
  { code: "ER", name: "Eritrea", image: "js/games/flags/images/ER.png" },
  { code: "EE", name: "Estonia", image: "js/games/flags/images/EE.png" },
  { code: "ET", name: "Ethiopia", image: "js/games/flags/images/ET.png" },
  { code: "FK", name: "Falkland Islands", image: "js/games/flags/images/FK.png" },
  { code: "FO", name: "Faroe Islands", image: "js/games/flags/images/FO.png" },
  { code: "FJ", name: "Fiji", image: "js/games/flags/images/FJ.png" },
  { code: "FI", name: "Finland", image: "js/games/flags/images/FI.png" },
  { code: "FR", name: "France", image: "js/games/flags/images/FR.png" },
  { code: "GF", name: "French Guiana", image: "js/games/flags/images/GF.png" },
  { code: "PF", name: "French Polynesia", image: "js/games/flags/images/PF.png" },
  { code: "GA", name: "Gabon", image: "js/games/flags/images/GA.png" },
  { code: "GM", name: "Gambia", image: "js/games/flags/images/GM.png" },
  { code: "GE", name: "Georgia", image: "js/games/flags/images/GE.png" },
  { code: "DE", name: "Germany", image: "js/games/flags/images/DE.png" },
  { code: "GH", name: "Ghana", image: "js/games/flags/images/GH.png" },
  { code: "GR", name: "Greece", image: "js/games/flags/images/GR.png" },
  { code: "GL", name: "Greenland", image: "js/games/flags/images/GL.png" },
  { code: "GD", name: "Grenada", image: "js/games/flags/images/GD.png" },
  { code: "GP", name: "Guadeloupe", image: "js/games/flags/images/GP.png" },
  { code: "GU", name: "Guam", image: "js/games/flags/images/GU.png" },
  { code: "GT", name: "Guatemala", image: "js/games/flags/images/GT.png" },
  { code: "GG", name: "Guernsey", image: "js/games/flags/images/GG.png" },
  { code: "GN", name: "Guinea", image: "js/games/flags/images/GN.png" },
  { code: "GW", name: "Guinea-Bissau", image: "js/games/flags/images/GW.png" },
  { code: "GY", name: "Guyana", image: "js/games/flags/images/GY.png" },
  { code: "HT", name: "Haiti", image: "js/games/flags/images/HT.png" },
  { code: "HN", name: "Honduras", image: "js/games/flags/images/HN.png" },
  { code: "HK", name: "Hong Kong", image: "js/games/flags/images/HK.png" },
  { code: "HU", name: "Hungary", image: "js/games/flags/images/HU.png" },
  { code: "IS", name: "Iceland", image: "js/games/flags/images/IS.png" },
  { code: "IN", name: "India", image: "js/games/flags/images/IN.png" },
  { code: "ID", name: "Indonesia", image: "js/games/flags/images/ID.png" },
  { code: "IR", name: "Iran", image: "js/games/flags/images/IR.png" },
  { code: "IQ", name: "Iraq", image: "js/games/flags/images/IQ.png" },
  { code: "IE", name: "Ireland", image: "js/games/flags/images/IE.png" },
  { code: "IM", name: "Isle of Man", image: "js/games/flags/images/IM.png" },
  { code: "IL", name: "Israel", image: "js/games/flags/images/IL.png" },
  { code: "IT", name: "Italy", image: "js/games/flags/images/IT.png" },
  { code: "JM", name: "Jamaica", image: "js/games/flags/images/JM.png" },
  { code: "JP", name: "Japan", image: "js/games/flags/images/JP.png" },
  { code: "JE", name: "Jersey", image: "js/games/flags/images/JE.png" },
  { code: "JO", name: "Jordan", image: "js/games/flags/images/JO.png" },
  { code: "KZ", name: "Kazakhstan", image: "js/games/flags/images/KZ.png" },
  { code: "KE", name: "Kenya", image: "js/games/flags/images/KE.png" },
  { code: "KI", name: "Kiribati", image: "js/games/flags/images/KI.png" },
  { code: "KW", name: "Kuwait", image: "js/games/flags/images/KW.png" },
  { code: "KG", name: "Kyrgyzstan", image: "js/games/flags/images/KG.png" },
  { code: "LA", name: "Laos", image: "js/games/flags/images/LA.png" },
  { code: "LV", name: "Latvia", image: "js/games/flags/images/LV.png" },
  { code: "LB", name: "Lebanon", image: "js/games/flags/images/LB.png" },
  { code: "LS", name: "Lesotho", image: "js/games/flags/images/LS.png" },
  { code: "LR", name: "Liberia", image: "js/games/flags/images/LR.png" },
  { code: "LY", name: "Libya", image: "js/games/flags/images/LY.png" },
  { code: "LI", name: "Liechtenstein", image: "js/games/flags/images/LI.png" },
  { code: "LT", name: "Lithuania", image: "js/games/flags/images/LT.png" },
  { code: "LU", name: "Luxembourg", image: "js/games/flags/images/LU.png" },
  { code: "MO", name: "Macao", image: "js/games/flags/images/MO.png" },
  { code: "MG", name: "Madagascar", image: "js/games/flags/images/MG.png" },
  { code: "MW", name: "Malawi", image: "js/games/flags/images/MW.png" },
  { code: "MY", name: "Malaysia", image: "js/games/flags/images/MY.png" },
  { code: "MV", name: "Maldives", image: "js/games/flags/images/MV.png" },
  { code: "ML", name: "Mali", image: "js/games/flags/images/ML.png" },
  { code: "MT", name: "Malta", image: "js/games/flags/images/MT.png" },
  { code: "MH", name: "Marshall Islands", image: "js/games/flags/images/MH.png" },
  { code: "MQ", name: "Martinique", image: "js/games/flags/images/MQ.png" },
  { code: "MR", name: "Mauritania", image: "js/games/flags/images/MR.png" },
  { code: "MU", name: "Mauritius", image: "js/games/flags/images/MU.png" },
  { code: "YT", name: "Mayotte", image: "js/games/flags/images/YT.png" },
  { code: "MX", name: "Mexico", image: "js/games/flags/images/MX.png" },
  { code: "FM", name: "Micronesia", image: "js/games/flags/images/FM.png" },
  { code: "MD", name: "Moldova", image: "js/games/flags/images/MD.png" },
  { code: "MC", name: "Monaco", image: "js/games/flags/images/MC.png" },
  { code: "MN", name: "Mongolia", image: "js/games/flags/images/MN.png" },
  { code: "ME", name: "Montenegro", image: "js/games/flags/images/ME.png" },
  { code: "MS", name: "Montserrat", image: "js/games/flags/images/MS.png" },
  { code: "MA", name: "Morocco", image: "js/games/flags/images/MA.png" },
  { code: "MZ", name: "Mozambique", image: "js/games/flags/images/MZ.png" },
  { code: "MM", name: "Myanmar", image: "js/games/flags/images/MM.png" },
  { code: "NA", name: "Namibia", image: "js/games/flags/images/NA.png" },
  { code: "NR", name: "Nauru", image: "js/games/flags/images/NR.png" },
  { code: "NP", name: "Nepal", image: "js/games/flags/images/NP.png" },
  { code: "NL", name: "Netherlands", image: "js/games/flags/images/NL.png" },
  { code: "NC", name: "New Caledonia", image: "js/games/flags/images/NC.png" },
  { code: "NZ", name: "New Zealand", image: "js/games/flags/images/NZ.png" },
  { code: "NI", name: "Nicaragua", image: "js/games/flags/images/NI.png" },
  { code: "NE", name: "Niger", image: "js/games/flags/images/NE.png" },
  { code: "NG", name: "Nigeria", image: "js/games/flags/images/NG.png" },
  { code: "NU", name: "Niue", image: "js/games/flags/images/NU.png" },
  { code: "NF", name: "Norfolk Island", image: "js/games/flags/images/NF.png" },
  { code: "KP", name: "North Korea", image: "js/games/flags/images/KP.png" },
  { code: "MK", name: "North Macedonia", image: "js/games/flags/images/MK.png" },
  { code: "MP", name: "Northern Mariana Islands", image: "js/games/flags/images/MP.png" },
  { code: "NO", name: "Norway", image: "js/games/flags/images/NO.png" },
  { code: "OM", name: "Oman", image: "js/games/flags/images/OM.png" },
  { code: "PK", name: "Pakistan", image: "js/games/flags/images/PK.png" },
  { code: "PW", name: "Palau", image: "js/games/flags/images/PW.png" },
  { code: "PS", name: "Palestine", image: "js/games/flags/images/PS.png" },
  { code: "PA", name: "Panama", image: "js/games/flags/images/PA.png" },
  { code: "PG", name: "Papua New Guinea", image: "js/games/flags/images/PG.png" },
  { code: "PY", name: "Paraguay", image: "js/games/flags/images/PY.png" },
  { code: "PE", name: "Peru", image: "js/games/flags/images/PE.png" },
  { code: "PH", name: "Philippines", image: "js/games/flags/images/PH.png" },
  { code: "PN", name: "Pitcairn Islands", image: "js/games/flags/images/PN.png" },
  { code: "PL", name: "Poland", image: "js/games/flags/images/PL.png" },
  { code: "PT", name: "Portugal", image: "js/games/flags/images/PT.png" },
  { code: "PR", name: "Puerto Rico", image: "js/games/flags/images/PR.png" },
  { code: "QA", name: "Qatar", image: "js/games/flags/images/QA.png" },
  { code: "RE", name: "Réunion", image: "js/games/flags/images/RE.png" },
  { code: "RO", name: "Romania", image: "js/games/flags/images/RO.png" },
  { code: "RU", name: "Russia", image: "js/games/flags/images/RU.png" },
  { code: "RW", name: "Rwanda", image: "js/games/flags/images/RW.png" },
  { code: "BL", name: "Saint Barthélemy", image: "js/games/flags/images/BL.png" },
  { code: "SH", name: "Saint Helena", image: "js/games/flags/images/SH.png" },
  { code: "KN", name: "Saint Kitts and Nevis", image: "js/games/flags/images/KN.png" },
  { code: "LC", name: "Saint Lucia", image: "js/games/flags/images/LC.png" },
  { code: "MF", name: "Saint Martin", image: "js/games/flags/images/MF.png" },
  { code: "PM", name: "Saint Pierre and Miquelon", image: "js/games/flags/images/PM.png" },
  { code: "VC", name: "Saint Vincent and the Grenadines", image: "js/games/flags/images/VC.png" },
  { code: "WS", name: "Samoa", image: "js/games/flags/images/WS.png" },
  { code: "SM", name: "San Marino", image: "js/games/flags/images/SM.png" },
  { code: "ST", name: "São Tomé and Príncipe", image: "js/games/flags/images/ST.png" },
  { code: "SA", name: "Saudi Arabia", image: "js/games/flags/images/SA.png" },
  { code: "SN", name: "Senegal", image: "js/games/flags/images/SN.png" },
  { code: "RS", name: "Serbia", image: "js/games/flags/images/RS.png" },
  { code: "SC", name: "Seychelles", image: "js/games/flags/images/SC.png" },
  { code: "SL", name: "Sierra Leone", image: "js/games/flags/images/SL.png" },
  { code: "SG", name: "Singapore", image: "js/games/flags/images/SG.png" },
  { code: "SX", name: "Sint Maarten", image: "js/games/flags/images/SX.png" },
  { code: "SK", name: "Slovakia", image: "js/games/flags/images/SK.png" },
  { code: "SI", name: "Slovenia", image: "js/games/flags/images/SI.png" },
  { code: "SB", name: "Solomon Islands", image: "js/games/flags/images/SB.png" },
  { code: "SO", name: "Somalia", image: "js/games/flags/images/SO.png" },
  { code: "ZA", name: "South Africa", image: "js/games/flags/images/ZA.png" },
  { code: "KR", name: "South Korea", image: "js/games/flags/images/KR.png" },
  { code: "SS", name: "South Sudan", image: "js/games/flags/images/SS.png" },
  { code: "ES", name: "Spain", image: "js/games/flags/images/ES.png" },
  { code: "LK", name: "Sri Lanka", image: "js/games/flags/images/LK.png" },
  { code: "SD", name: "Sudan", image: "js/games/flags/images/SD.png" },
  { code: "SR", name: "Suriname", image: "js/games/flags/images/SR.png" },
  { code: "SE", name: "Sweden", image: "js/games/flags/images/SE.png" },
  { code: "CH", name: "Switzerland", image: "js/games/flags/images/CH.png" },
  { code: "SY", name: "Syria", image: "js/games/flags/images/SY.png" },
];