export const flagsConfig = [

  // --- EUROPE ---
  { code: "AL", name: "Albania", image: "webapp/js/games/flags/images/al.png", region: "Europe" },
  { code: "AD", name: "Andorra", image: "webapp/js/games/flags/images/ad.png", region: "Europe" },
  { code: "AT", name: "Austria", image: "webapp/js/games/flags/images/at.png", region: "Europe" },
  { code: "BY", name: "Belarus", image: "webapp/js/games/flags/images/by.png", region: "Europe" },
  { code: "BE", name: "Belgium", image: "webapp/js/games/flags/images/be.png", region: "Europe" },
  { code: "BA", name: "Bosnia and Herzegovina", image: "webapp/js/games/flags/images/ba.png", region: "Europe" },
  { code: "BG", name: "Bulgaria", image: "webapp/js/games/flags/images/bg.png", region: "Europe" },
  { code: "HR", name: "Croatia", image: "webapp/js/games/flags/images/hr.png", region: "Europe" },
  { code: "CY", name: "Cyprus", image: "webapp/js/games/flags/images/cy.png", region: "Europe" },
  { code: "CZ", name: "Czech Republic", image: "webapp/js/games/flags/images/cz.png", region: "Europe" },
  { code: "DK", name: "Denmark", image: "webapp/js/games/flags/images/dk.png", region: "Europe" },
  { code: "EE", name: "Estonia", image: "webapp/js/games/flags/images/ee.png", region: "Europe" },
  { code: "FO", name: "Faroe Islands", image: "webapp/js/games/flags/images/fo.png", region: "Europe" },
  { code: "FI", name: "Finland", image: "webapp/js/games/flags/images/fi.png", region: "Europe" },
  { code: "FR", name: "France", image: "webapp/js/games/flags/images/fr.png", region: "Europe" },
  { code: "GE", name: "Georgia", image: "webapp/js/games/flags/images/ge.png", region: "Europe" },
  { code: "DE", name: "Germany", image: "webapp/js/games/flags/images/de.png", region: "Europe" },
  { code: "GR", name: "Greece", image: "webapp/js/games/flags/images/gr.png", region: "Europe" },
  { code: "GG", name: "Guernsey", image: "webapp/js/games/flags/images/gg.png", region: "Europe" },
  { code: "HU", name: "Hungary", image: "webapp/js/games/flags/images/hu.png", region: "Europe" },
  { code: "IS", name: "Iceland", image: "webapp/js/games/flags/images/is.png", region: "Europe" },
  { code: "IE", name: "Ireland", image: "webapp/js/games/flags/images/ie.png", region: "Europe" },
  { code: "IM", name: "Isle of Man", image: "webapp/js/games/flags/images/im.png", region: "Europe" },
  { code: "IT", name: "Italy", image: "webapp/js/games/flags/images/it.png", region: "Europe" },
  { code: "JE", name: "Jersey", image: "webapp/js/games/flags/images/je.png", region: "Europe" },
  { code: "LV", name: "Latvia", image: "webapp/js/games/flags/images/lv.png", region: "Europe" },
  { code: "LI", name: "Liechtenstein", image: "webapp/js/games/flags/images/li.png", region: "Europe" },
  { code: "LT", name: "Lithuania", image: "webapp/js/games/flags/images/lt.png", region: "Europe" },
  { code: "LU", name: "Luxembourg", image: "webapp/js/games/flags/images/lu.png", region: "Europe" },
  { code: "MT", name: "Malta", image: "webapp/js/games/flags/images/mt.png", region: "Europe" },
  { code: "MD", name: "Moldova", image: "webapp/js/games/flags/images/md.png", region: "Europe" },
  { code: "MC", name: "Monaco", image: "webapp/js/games/flags/images/mc.png", region: "Europe" },
  { code: "ME", name: "Montenegro", image: "webapp/js/games/flags/images/me.png", region: "Europe" },
  { code: "NL", name: "Netherlands", image: "webapp/js/games/flags/images/nl.png", region: "Europe" },
  { code: "MK", name: "North Macedonia", image: "webapp/js/games/flags/images/mk.png", region: "Europe" },
  { code: "NO", name: "Norway", image: "webapp/js/games/flags/images/no.png", region: "Europe" },
  { code: "PL", name: "Poland", image: "webapp/js/games/flags/images/pl.png", region: "Europe" },
  { code: "PT", name: "Portugal", image: "webapp/js/games/flags/images/pt.png", region: "Europe" },
  { code: "RO", name: "Romania", image: "webapp/js/games/flags/images/ro.png", region: "Europe" },
  { code: "RU", name: "Russia", image: "webapp/js/games/flags/images/ru.png", region: "Europe" },
  { code: "SM", name: "San Marino", image: "webapp/js/games/flags/images/sm.png", region: "Europe" },
  { code: "RS", name: "Serbia", image: "webapp/js/games/flags/images/rs.png", region: "Europe" },
  { code: "SK", name: "Slovakia", image: "webapp/js/games/flags/images/sk.png", region: "Europe" },
  { code: "SI", name: "Slovenia", image: "webapp/js/games/flags/images/si.png", region: "Europe" },
  { code: "ES", name: "Spain", image: "webapp/js/games/flags/images/es.png", region: "Europe" },
  { code: "SE", name: "Sweden", image: "webapp/js/games/flags/images/se.png", region: "Europe" },
  { code: "CH", name: "Switzerland", image: "webapp/js/games/flags/images/ch.png", region: "Europe" },

  // --- ASIA & OCEANIA ---
  { code: "AF", name: "Afghanistan", image: "webapp/js/games/flags/images/af.png", region: "Asia-Oceania" },
  { code: "AS", name: "American Samoa", image: "webapp/js/games/flags/images/as.png", region: "Asia-Oceania" },
  { code: "AM", name: "Armenia", image: "webapp/js/games/flags/images/am.png", region: "Asia-Oceania" },
  { code: "AU", name: "Australia", image: "webapp/js/games/flags/images/au.png", region: "Asia-Oceania" },
  { code: "AZ", name: "Azerbaijan", image: "webapp/js/games/flags/images/az.png", region: "Asia-Oceania" },
  { code: "BH", name: "Bahrain", image: "webapp/js/games/flags/images/bh.png", region: "Asia-Oceania" },
  { code: "BD", name: "Bangladesh", image: "webapp/js/games/flags/images/bd.png", region: "Asia-Oceania" },
  { code: "BT", name: "Bhutan", image: "webapp/js/games/flags/images/bt.png", region: "Asia-Oceania" },
  { code: "IO", name: "British Indian Ocean Territory", image: "webapp/js/games/flags/images/io.png", region: "Asia-Oceania" },
  { code: "BN", name: "Brunei", image: "webapp/js/games/flags/images/bn.png", region: "Asia-Oceania" },
  { code: "KH", name: "Cambodia", image: "webapp/js/games/flags/images/kh.png", region: "Asia-Oceania" },
  { code: "CN", name: "China", image: "webapp/js/games/flags/images/cn.png", region: "Asia-Oceania" },
  { code: "CX", name: "Christmas Island", image: "webapp/js/games/flags/images/cx.png", region: "Asia-Oceania" },
  { code: "CC", name: "Cocos (Keeling) Islands", image: "webapp/js/games/flags/images/cc.png", region: "Asia-Oceania" },
  { code: "CK", name: "Cook Islands", image: "webapp/js/games/flags/images/ck.png", region: "Asia-Oceania" },
  { code: "FJ", name: "Fiji", image: "webapp/js/games/flags/images/fj.png", region: "Asia-Oceania" },
  { code: "PF", name: "French Polynesia", image: "webapp/js/games/flags/images/pf.png", region: "Asia-Oceania" },
  { code: "GU", name: "Guam", image: "webapp/js/games/flags/images/gu.png", region: "Asia-Oceania" },
  { code: "HK", name: "Hong Kong", image: "webapp/js/games/flags/images/hk.png", region: "Asia-Oceania" },
  { code: "IN", name: "India", image: "webapp/js/games/flags/images/in.png", region: "Asia-Oceania" },
  { code: "ID", name: "Indonesia", image: "webapp/js/games/flags/images/id.png", region: "Asia-Oceania" },
  { code: "IR", name: "Iran", image: "webapp/js/games/flags/images/ir.png", region: "Asia-Oceania" },
  { code: "IQ", name: "Iraq", image: "webapp/js/games/flags/images/iq.png", region: "Asia-Oceania" },
  { code: "IL", name: "Israel", image: "webapp/js/games/flags/images/il.png", region: "Asia-Oceania" },
  { code: "JP", name: "Japan", image: "webapp/js/games/flags/images/jp.png", region: "Asia-Oceania" },
  { code: "JO", name: "Jordan", image: "webapp/js/games/flags/images/jo.png", region: "Asia-Oceania" },
  { code: "KZ", name: "Kazakhstan", image: "webapp/js/games/flags/images/kz.png", region: "Asia-Oceania" },
  { code: "KI", name: "Kiribati", image: "webapp/js/games/flags/images/ki.png", region: "Asia-Oceania" },
  { code: "KW", name: "Kuwait", image: "webapp/js/games/flags/images/kw.png", region: "Asia-Oceania" },
  { code: "KG", name: "Kyrgyzstan", image: "webapp/js/games/flags/images/kg.png", region: "Asia-Oceania" },
  { code: "LA", name: "Laos", image: "webapp/js/games/flags/images/la.png", region: "Asia-Oceania" },
  { code: "LB", name: "Lebanon", image: "webapp/js/games/flags/images/lb.png", region: "Asia-Oceania" },
  { code: "MO", name: "Macao", image: "webapp/js/games/flags/images/mo.png", region: "Asia-Oceania" },
  { code: "MY", name: "Malaysia", image: "webapp/js/games/flags/images/my.png", region: "Asia-Oceania" },
  { code: "MV", name: "Maldives", image: "webapp/js/games/flags/images/mv.png", region: "Asia-Oceania" },
  { code: "MH", name: "Marshall Islands", image: "webapp/js/games/flags/images/mh.png", region: "Asia-Oceania" },
  { code: "FM", name: "Micronesia", image: "webapp/js/games/flags/images/fm.png", region: "Asia-Oceania" },
  { code: "MN", name: "Mongolia", image: "webapp/js/games/flags/images/mn.png", region: "Asia-Oceania" },
  { code: "MM", name: "Myanmar", image: "webapp/js/games/flags/images/mm.png", region: "Asia-Oceania" },
  { code: "NR", name: "Nauru", image: "webapp/js/games/flags/images/nr.png", region: "Asia-Oceania" },
  { code: "NP", name: "Nepal", image: "webapp/js/games/flags/images/np.png", region: "Asia-Oceania" },
  { code: "NC", name: "New Caledonia", image: "webapp/js/games/flags/images/nc.png", region: "Asia-Oceania" },
  { code: "NZ", name: "New Zealand", image: "webapp/js/games/flags/images/nz.png", region: "Asia-Oceania" },
  { code: "NU", name: "Niue", image: "webapp/js/games/flags/images/nu.png", region: "Asia-Oceania" },
  { code: "NF", name: "Norfolk Island", image: "webapp/js/games/flags/images/nf.png", region: "Asia-Oceania" },
  { code: "KP", name: "North Korea", image: "webapp/js/games/flags/images/kp.png", region: "Asia-Oceania" },
  { code: "MP", name: "Northern Mariana Islands", image: "webapp/js/games/flags/images/mp.png", region: "Asia-Oceania" },
  { code: "OM", name: "Oman", image: "webapp/js/games/flags/images/om.png", region: "Asia-Oceania" },
  { code: "PK", name: "Pakistan", image: "webapp/js/games/flags/images/pk.png", region: "Asia-Oceania" },
  { code: "PW", name: "Palau", image: "webapp/js/games/flags/images/pw.png", region: "Asia-Oceania" },
  { code: "PS", name: "Palestine", image: "webapp/js/games/flags/images/ps.png", region: "Asia-Oceania" },
  { code: "PG", name: "Papua New Guinea", image: "webapp/js/games/flags/images/pg.png", region: "Asia-Oceania" },
  { code: "PH", name: "Philippines", image: "webapp/js/games/flags/images/ph.png", region: "Asia-Oceania" },
  { code: "PN", name: "Pitcairn Islands", image: "webapp/js/games/flags/images/pn.png", region: "Asia-Oceania" },
  { code: "QA", name: "Qatar", image: "webapp/js/games/flags/images/qa.png", region: "Asia-Oceania" },
  { code: "WS", name: "Samoa", image: "webapp/js/games/flags/images/ws.png", region: "Asia-Oceania" },
  { code: "SA", name: "Saudi Arabia", image: "webapp/js/games/flags/images/sa.png", region: "Asia-Oceania" },
  { code: "SG", name: "Singapore", image: "webapp/js/games/flags/images/sg.png", region: "Asia-Oceania" },
  { code: "SB", name: "Solomon Islands", image: "webapp/js/games/flags/images/sb.png", region: "Asia-Oceania" },
  { code: "KR", name: "South Korea", image: "webapp/js/games/flags/images/kr.png", region: "Asia-Oceania" },
  { code: "LK", name: "Sri Lanka", image: "webapp/js/games/flags/images/lk.png", region: "Asia-Oceania" },
  { code: "SY", name: "Syria", image: "webapp/js/games/flags/images/sy.png", region: "Asia-Oceania" },

  // --- AMERICAS ---
  { code: "AI", name: "Anguilla", image: "webapp/js/games/flags/images/ai.png", region: "Americas" },
  { code: "AG", name: "Antigua and Barbuda", image: "webapp/js/games/flags/images/ag.png", region: "Americas" },
  { code: "AR", name: "Argentina", image: "webapp/js/games/flags/images/ar.png", region: "Americas" },
  { code: "AW", name: "Aruba", image: "webapp/js/games/flags/images/aw.png", region: "Americas" },
  { code: "BS", name: "Bahamas", image: "webapp/js/games/flags/images/bs.png", region: "Americas" },
  { code: "BB", name: "Barbados", image: "webapp/js/games/flags/images/bb.png", region: "Americas" },
  { code: "BZ", name: "Belize", image: "webapp/js/games/flags/images/bz.png", region: "Americas" },
  { code: "BM", name: "Bermuda", image: "webapp/js/games/flags/images/bm.png", region: "Americas" },
  { code: "BO", name: "Bolivia", image: "webapp/js/games/flags/images/bo.png", region: "Americas" },
  { code: "BR", name: "Brazil", image: "webapp/js/games/flags/images/br.png", region: "Americas" },
  { code: "CA", name: "Canada", image: "webapp/js/games/flags/images/ca.png", region: "Americas" },
  { code: "KY", name: "Cayman Islands", image: "webapp/js/games/flags/images/ky.png", region: "Americas" },
  { code: "CL", name: "Chile", image: "webapp/js/games/flags/images/cl.png", region: "Americas" },
  { code: "CO", name: "Colombia", image: "webapp/js/games/flags/images/co.png", region: "Americas" },
  { code: "CR", name: "Costa Rica", image: "webapp/js/games/flags/images/cr.png", region: "Americas" },
  { code: "CU", name: "Cuba", image: "webapp/js/games/flags/images/cu.png", region: "Americas" },
  { code: "DM", name: "Dominica", image: "webapp/js/games/flags/images/dm.png", region: "Americas" },
  { code: "DO", name: "Dominican Republic", image: "webapp/js/games/flags/images/do.png", region: "Americas" },
  { code: "EC", name: "Ecuador", image: "webapp/js/games/flags/images/ec.png", region: "Americas" },
  { code: "SV", name: "El Salvador", image: "webapp/js/games/flags/images/sv.png", region: "Americas" },
  { code: "FK", name: "Falkland Islands", image: "webapp/js/games/flags/images/fk.png", region: "Americas" },
  { code: "GF", name: "French Guiana", image: "webapp/js/games/flags/images/gf.png", region: "Americas" },
  { code: "GL", name: "Greenland", image: "webapp/js/games/flags/images/gl.png", region: "Americas" },
  { code: "GD", name: "Grenada", image: "webapp/js/games/flags/images/gd.png", region: "Americas" },
  { code: "GP", name: "Guadeloupe", image: "webapp/js/games/flags/images/gp.png", region: "Americas" },
  { code: "GT", name: "Guatemala", image: "webapp/js/games/flags/images/gt.png", region: "Americas" },
  { code: "GY", name: "Guyana", image: "webapp/js/games/flags/images/gy.png", region: "Americas" },
  { code: "HT", name: "Haiti", image: "webapp/js/games/flags/images/ht.png", region: "Americas" },
  { code: "HN", name: "Honduras", image: "webapp/js/games/flags/images/hn.png", region: "Americas" },
  { code: "JM", name: "Jamaica", image: "webapp/js/games/flags/images/jm.png", region: "Americas" },
  { code: "MQ", name: "Martinique", image: "webapp/js/games/flags/images/mq.png", region: "Americas" },
  { code: "MX", name: "Mexico", image: "webapp/js/games/flags/images/mx.png", region: "Americas" },
  { code: "MS", name: "Montserrat", image: "webapp/js/games/flags/images/ms.png", region: "Americas" },
  { code: "NI", name: "Nicaragua", image: "webapp/js/games/flags/images/ni.png", region: "Americas" },
  { code: "PA", name: "Panama", image: "webapp/js/games/flags/images/pa.png", region: "Americas" },
  { code: "PY", name: "Paraguay", image: "webapp/js/games/flags/images/py.png", region: "Americas" },
  { code: "PE", name: "Peru", image: "webapp/js/games/flags/images/pe.png", region: "Americas" },
  { code: "PR", name: "Puerto Rico", image: "webapp/js/games/flags/images/pr.png", region: "Americas" },
  { code: "BL", name: "Saint Barthélemy", image: "webapp/js/games/flags/images/bl.png", region: "Americas" },
  { code: "KN", name: "Saint Kitts and Nevis", image: "webapp/js/games/flags/images/kn.png", region: "Americas" },
  { code: "LC", name: "Saint Lucia", image: "webapp/js/games/flags/images/lc.png", region: "Americas" },
  { code: "MF", name: "Saint Martin", image: "webapp/js/games/flags/images/mf.png", region: "Americas" },
  { code: "PM", name: "Saint Pierre and Miquelon", image: "webapp/js/games/flags/images/pm.png", region: "Americas" },
  { code: "VC", name: "Saint Vincent and the Grenadines", image: "webapp/js/games/flags/images/vc.png", region: "Americas" },
  { code: "SX", name: "Sint Maarten", image: "webapp/js/games/flags/images/sx.png", region: "Americas" },
  { code: "SR", name: "Suriname", image: "webapp/js/games/flags/images/sr.png", region: "Americas" },

  // --- AFRICA ---
  { code: "DZ", name: "Algeria", image: "webapp/js/games/flags/images/dz.png", region: "Africa" },
  { code: "AO", name: "Angola", image: "webapp/js/games/flags/images/ao.png", region: "Africa" },
  { code: "BJ", name: "Benin", image: "webapp/js/games/flags/images/bj.png", region: "Africa" },
  { code: "BW", name: "Botswana", image: "webapp/js/games/flags/images/bw.png", region: "Africa" },
  { code: "BF", name: "Burkina Faso", image: "webapp/js/games/flags/images/bf.png", region: "Africa" },
  { code: "BI", name: "Burundi", image: "webapp/js/games/flags/images/bi.png", region: "Africa" },
  { code: "CV", name: "Cabo Verde", image: "webapp/js/games/flags/images/cv.png", region: "Africa" },
  { code: "CM", name: "Cameroon", image: "webapp/js/games/flags/images/cm.png", region: "Africa" },
  { code: "CF", name: "Central African Republic", image: "webapp/js/games/flags/images/cf.png", region: "Africa" },
  { code: "TD", name: "Chad", image: "webapp/js/games/flags/images/td.png", region: "Africa" },
  { code: "KM", name: "Comoros", image: "webapp/js/games/flags/images/km.png", region: "Africa" },
  { code: "CG", name: "Congo Republic", image: "webapp/js/games/flags/images/cg.png", region: "Africa" },
  { code: "CD", name: "Congo (DRC)", image: "webapp/js/games/flags/images/cd.png", region: "Africa" },
  { code: "CI", name: "Côte d'Ivoire", image: "webapp/js/games/flags/images/ci.png", region: "Africa" },
  { code: "DJ", name: "Djibouti", image: "webapp/js/games/flags/images/dj.png", region: "Africa" },
  { code: "EG", name: "Egypt", image: "webapp/js/games/flags/images/eg.png", region: "Africa" },
  { code: "GQ", name: "Equatorial Guinea", image: "webapp/js/games/flags/images/gq.png", region: "Africa" },
  { code: "ER", name: "Eritrea", image: "webapp/js/games/flags/images/er.png", region: "Africa" },
  { code: "ET", name: "Ethiopia", image: "webapp/js/games/flags/images/et.png", region: "Africa" },
  { code: "GA", name: "Gabon", image: "webapp/js/games/flags/images/ga.png", region: "Africa" },
  { code: "GM", name: "Gambia", image: "webapp/js/games/flags/images/gm.png", region: "Africa" },
  { code: "GH", name: "Ghana", image: "webapp/js/games/flags/images/gh.png", region: "Africa" },
  { code: "GN", name: "Guinea", image: "webapp/js/games/flags/images/gn.png", region: "Africa" },
  { code: "GW", name: "Guinea-Bissau", image: "webapp/js/games/flags/images/gw.png", region: "Africa" },
  { code: "KE", name: "Kenya", image: "webapp/js/games/flags/images/ke.png", region: "Africa" },
  { code: "LS", name: "Lesotho", image: "webapp/js/games/flags/images/ls.png", region: "Africa" },
  { code: "LR", name: "Liberia", image: "webapp/js/games/flags/images/lr.png", region: "Africa" },
  { code: "LY", name: "Libya", image: "webapp/js/games/flags/images/ly.png", region: "Africa" },
  { code: "MG", name: "Madagascar", image: "webapp/js/games/flags/images/mg.png", region: "Africa" },
  { code: "MW", name: "Malawi", image: "webapp/js/games/flags/images/mw.png", region: "Africa" },
  { code: "ML", name: "Mali", image: "webapp/js/games/flags/images/ml.png", region: "Africa" },
  { code: "MR", name: "Mauritania", image: "webapp/js/games/flags/images/mr.png", region: "Africa" },
  { code: "MU", name: "Mauritius", image: "webapp/js/games/flags/images/mu.png", region: "Africa" },
  { code: "YT", name: "Mayotte", image: "webapp/js/games/flags/images/yt.png", region: "Africa" },
  { code: "MA", name: "Morocco", image: "webapp/js/games/flags/images/ma.png", region: "Africa" },
  { code: "MZ", name: "Mozambique", image: "webapp/js/games/flags/images/mz.png", region: "Africa" },
  { code: "NA", name: "Namibia", image: "webapp/js/games/flags/images/na.png", region: "Africa" },
  { code: "NE", name: "Niger", image: "webapp/js/games/flags/images/ne.png", region: "Africa" },
  { code: "NG", name: "Nigeria", image: "webapp/js/games/flags/images/ng.png", region: "Africa" },
  { code: "RE", name: "Réunion", image: "webapp/js/games/flags/images/re.png", region: "Africa" },
  { code: "RW", name: "Rwanda", image: "webapp/js/games/flags/images/rw.png", region: "Africa" },
  { code: "SH", name: "Saint Helena", image: "webapp/js/games/flags/images/sh.png", region: "Africa" },
  { code: "ST", name: "São Tomé and Príncipe", image: "webapp/js/games/flags/images/st.png", region: "Africa" },
  { code: "SN", name: "Senegal", image: "webapp/js/games/flags/images/sn.png", region: "Africa" },
  { code: "SC", name: "Seychelles", image: "webapp/js/games/flags/images/sc.png", region: "Africa" },
  { code: "SL", name: "Sierra Leone", image: "webapp/js/games/flags/images/sl.png", region: "Africa" },
  { code: "SO", name: "Somalia", image: "webapp/js/games/flags/images/so.png", region: "Africa" },
  { code: "ZA", name: "South Africa", image: "webapp/js/games/flags/images/za.png", region: "Africa" },
  { code: "SS", name: "South Sudan", image: "webapp/js/games/flags/images/ss.png", region: "Africa" },
  { code: "SD", name: "Sudan", image: "webapp/js/games/flags/images/sd.png", region: "Africa" },

  // --- OTHER ---
  { code: "AQ", name: "Antarctica", image: "webapp/js/games/flags/images/aq.png", region: "Other" }

];