export const HL_DATA = {
    stars: {
        title: "CELEB CLASH",
        unit: "followers",
        color: "#a855f7", // Фиолетовый
        items: [
            { name: "Cristiano Ronaldo", value: 672000000, desc: "Footballer", img: "/js/games/highlow/images/star/ronaldo.jpg" },
            { name: "Lionel Messi", value: 511000000, desc: "Footballer", img: "/js/games/highlow/images/star/messi.jpg" },
            { name: "Selena Gomez", value: 415000000, desc: "Singer", img: "/js/games/highlow/images/star/gomez.jpg" },
            { name: "Kylie Jenner", value: 390000000, desc: "Business", img: "/js/games/highlow/images/star/kylie.jpg" },
            { name: "Dwayne Johnson", value: 390000000, desc: "Actor", img: "/js/games/highlow/images/star/rock.jpg" },
            { name: "Ariana Grande", value: 371000000, desc: "Singer", img: "/js/games/highlow/images/star/ariana.jpg" },
            { name: "Kim Kardashian", value: 353000000, desc: "TV Star", img: "/js/games/highlow/images/star/kim.jpg" },
            { name: "Beyoncé", value: 307000000, desc: "Singer", img: "/js/games/highlow/images/star/beyonce.jpg" },
            { name: "Khloé Kardashian", value: 299000000, desc: "TV Star", img: "/js/games/highlow/images/star/khloe.jpg" },
            { name: "Justin Bieber", value: 292000000, desc: "Singer", img: "/js/games/highlow/images/star/bieber.jpg" },
            { name: "MrBeast", value: 85000000, desc: "YouTuber", img: "/js/games/highlow/images/star/mrbeast.jpg" },
            { name: "Taylor Swift", value: 280000000, desc: "Singer", img: "/js/games/highlow/images/star/swift.jpg" },
            { name: "Kendall Jenner", value: 284000000, desc: "Model", img: "/js/games/highlow/images/star/kendall.jpg" },
            { name: "Jennifer Lopez", value: 246000000, desc: "Singer/Actress", img: "/js/games/highlow/images/star/jlo.jpg" },
            { name: "Neymar Jr", value: 234000000, desc: "Footballer", img: "/js/games/highlow/images/star/neymar.jpg" },
            { name: "Nicki Minaj", value: 230000000, desc: "Rapper", img: "/js/games/highlow/images/star/minaj.jpg" },
            { name: "Miley Cyrus", value: 210000000, desc: "Singer", img: "/js/games/highlow/images/star/miley.jpg" },
            { name: "Katy Perry", value: 201000000, desc: "Singer", img: "/js/games/highlow/images/star/katy.jpg" },
            { name: "Zendaya", value: 176000000, desc: "Actress", img: "/js/games/highlow/images/star/zendaya.jpg" },
            { name: "Kevin Hart", value: 176000000, desc: "Comedian", img: "/js/games/highlow/images/star/hart.jpg" },
            { name: "Cardi B", value: 164000000, desc: "Rapper", img: "/js/games/highlow/images/star/cardi.jpg" },
            { name: "LeBron James", value: 157000000, desc: "Basketballer", img: "/js/games/highlow/images/star/lebron.jpg" },
            { name: "Rihanna", value: 149000000, desc: "Singer/Business", img: "/js/games/highlow/images/star/rihanna.jpg" },
            { name: "Drake", value: 141000000, desc: "Rapper", img: "/js/games/highlow/images/star/drake.jpg" },
            { name: "Billie Eilish", value: 125000000, desc: "Singer", img: "/js/games/highlow/images/star/billie.jpg" },
            { name: "Kylian Mbappé", value: 130000000, desc: "Footballer", img: "/js/games/highlow/images/star/mbappe.jpg" },
            { name: "Dua Lipa", value: 88000000, desc: "Singer", img: "/js/games/highlow/images/star/dualipa.jpg" },
            { name: "Robert Downey Jr", value: 58000000, desc: "Iron Man", img: "/js/games/highlow/images/star/rdj.jpg" },
            { name: "Tom Holland", value: 63000000, desc: "Spider-Man", img: "/js/games/highlow/images/star/holland.jpg" },
            { name: "Johnny Depp", value: 29000000, desc: "Jack Sparrow", img: "/js/games/highlow/images/star/depp.jpg" },
            { name: "Chris Hemsworth", value: 58000000, desc: "Thor", img: "/js/games/highlow/images/star/thor.jpg" },
            { name: "Cillian Murphy", value: 2000000, desc: "Peaky Blinders", img: "/js/games/highlow/images/star/cillian.jpg" },
            { name: "Vin Diesel", value: 105000000, desc: "Fast & Furious", img: "/js/games/highlow/images/star/vin.jpg" },
            { name: "Will Smith", value: 70000000, desc: "Actor", img: "/js/games/highlow/images/star/wsmith.jpg" },
            { name: "Jackie Chan", value: 7800000, desc: "Legend", img: "/js/games/highlow/images/star/jackie.jpg" },
            { name: "Leonardo DiCaprio", value: 60000000, desc: "Actor", img: "/js/games/highlow/images/star/leo.jpg" },
            { name: "Millie Bobby Brown", value: 73000000, desc: "Stranger Things", img: "/js/games/highlow/images/star/millie.jpg" },
            { name: "Henry Cavill", value: 29000000, desc: "Superman", img: "/js/games/highlow/images/star/cavill.jpg" },
            { name: "Ryan Reynolds", value: 50000000, desc: "Deadpool", img: "/js/games/highlow/images/star/reynolds.jpg" },
            { name: "Gal Gadot", value: 107000000, desc: "Wonder Woman", img: "/js/games/highlow/images/star/gadot.jpg" },
            { name: "Emma Watson", value: 72000000, desc: "Harry Potter", img: "/js/games/highlow/images/star/emma.jpg" },
            { name: "Lady Gaga", value: 63000000, desc: "Singer/Actress", img: "/js/games/highlow/images/star/gaga.jpg" },
            { name: "Jason Statham", value: 44000000, desc: "Action Star", img: "/js/games/highlow/images/star/statham.jpg" },
            { name: "Tom Cruise", value: 15000000, desc: "Mission Impossible", img: "/js/games/highlow/images/star/cruise.jpg" },
        ]
    },

    global: {
        title: "POPULATION",
        unit: "people",
        color: "#3b82f6", // Синий
        items: [
            { name: "India", value: 1428000000, desc: "Asia", img: "/js/games/highlow/images/flags/india.jpg" },
            { name: "China", value: 1425000000, desc: "Asia", img: "/js/games/highlow/images/flags/china.jpg" },
            { name: "USA", value: 340000000, desc: "North America", img: "/js/games/highlow/images/flags/usa.jpg" },
            { name: "Indonesia", value: 277000000, desc: "Asia", img: "/js/games/highlow/images/flags/indonesia.jpg" },
            { name: "Pakistan", value: 240000000, desc: "Asia", img: "/js/games/highlow/images/flags/pakistan.jpg" },
            { name: "Nigeria", value: 223000000, desc: "Africa", img: "/js/games/highlow/images/flags/nigeria.jpg" },
            { name: "Brazil", value: 216000000, desc: "South America", img: "/js/games/highlow/images/flags/brazil.jpg" },
            { name: "Bangladesh", value: 173000000, desc: "Asia", img: "/js/games/highlow/images/flags/bangladesh.jpg" },
            { name: "Russia", value: 144000000, desc: "Europe / Asia", img: "/js/games/highlow/images/flags/russia.jpg" },
            { name: "Mexico", value: 128000000, desc: "North America", img: "/js/games/highlow/images/flags/mexico.jpg" },
            { name: "Japan", value: 123000000, desc: "Asia", img: "/js/games/highlow/images/flags/japan.jpg" },
            { name: "Philippines", value: 117000000, desc: "Asia", img: "/js/games/highlow/images/flags/philippines.jpg" },
            { name: "Egypt", value: 112000000, desc: "Africa", img: "/js/games/highlow/images/flags/egypt.jpg" },
            { name: "Vietnam", value: 99000000, desc: "Asia", img: "/js/games/highlow/images/flags/vietnam.jpg" },
            { name: "Turkey", value: 85000000, desc: "Europe / Asia", img: "/js/games/highlow/images/flags/turkey.jpg" },
            { name: "Germany", value: 83000000, desc: "Europe", img: "/js/games/highlow/images/flags/germany.jpg" },
            { name: "Thailand", value: 71000000, desc: "Asia", img: "/js/games/highlow/images/flags/thailand.jpg" },
            { name: "France", value: 68000000, desc: "Europe", img: "/js/games/highlow/images/flags/france.jpg" },
            { name: "United Kingdom", value: 67000000, desc: "Europe", img: "/js/games/highlow/images/flags/uk.jpg" },
            { name: "Italy", value: 59000000, desc: "Europe", img: "/js/games/highlow/images/flags/italy.jpg" },
            { name: "South Africa", value: 60000000, desc: "Africa", img: "/js/games/highlow/images/flags/south_africa.jpg" },
            { name: "South Korea", value: 51000000, desc: "Asia", img: "/js/games/highlow/images/flags/south_korea.jpg" },
            { name: "Spain", value: 47000000, desc: "Europe", img: "/js/games/highlow/images/flags/spain.jpg" },
            { name: "Argentina", value: 46000000, desc: "South America", img: "/js/games/highlow/images/flags/argentina.jpg" },
            { name: "Canada", value: 39000000, desc: "North America", img: "/js/games/highlow/images/flags/canada.jpg" },
            { name: "Poland", value: 37000000, desc: "Europe", img: "/js/games/highlow/images/flags/poland.jpg" },
            { name: "Australia", value: 26000000, desc: "Oceania", img: "/js/games/highlow/images/flags/australia.jpg" },
            { name: "Kazakhstan", value: 20000000, desc: "Central Asia", img: "/js/games/highlow/images/flags/kazakhstan.jpg" },
            { name: "Netherlands", value: 17000000, desc: "Europe", img: "/js/games/highlow/images/flags/netherlands.jpg" },
            { name: "Switzerland", value: 8900000, desc: "Europe", img: "/js/games/highlow/images/flags/switzerland.jpg" },
            { name: "UAE", value: 9400000, desc: "Middle East", img: "/js/games/highlow/images/flags/uae.jpg" },
            { name: "Norway", value: 5500000, desc: "Europe", img: "/js/games/highlow/images/flags/norway.jpg" },
            { name: "Singapore", value: 5600000, desc: "Asia", img: "/js/games/highlow/images/flags/singapore.jpg" },
            { name: "Iceland", value: 380000, desc: "Europe", img: "/js/games/highlow/images/flags/iceland.jpg" },
            { name: "Ethiopia", value: 126000000, desc: "Africa", img: "/js/games/highlow/images/flags/ethiopia.jpg" },
            { name: "DR Congo", value: 102000000, desc: "Africa", img: "/js/games/highlow/images/flags/dr_congo.jpg" },
            { name: "Iran", value: 89000000, desc: "Middle East", img: "/js/games/highlow/images/flags/iran.jpg" },
            { name: "Colombia", value: 52000000, desc: "South America", img: "/js/games/highlow/images/flags/colombia.jpg" },
            { name: "Kenya", value: 55000000, desc: "Africa", img: "/js/games/highlow/images/flags/kenya.jpg" },
            { name: "Myanmar", value: 54000000, desc: "Asia", img: "/js/games/highlow/images/flags/myanmar.jpg" },
            { name: "Tanzania", value: 65000000, desc: "Africa", img: "/js/games/highlow/images/flags/tanzania.jpg" },
            { name: "Algeria", value: 45000000, desc: "Africa", img: "/js/games/highlow/images/flags/algeria.jpg" },
            { name: "Ukraine", value: 37000000, desc: "Europe", img: "/js/games/highlow/images/flags/ukraine.jpg" },
            { name: "Iraq", value: 45000000, desc: "Middle East", img: "/js/games/highlow/images/flags/iraq.jpg" },
            { name: "Afghanistan", value: 42000000, desc: "Asia", img: "/js/games/highlow/images/flags/afghanistan.jpg" },
            { name: "Morocco", value: 37000000, desc: "Africa", img: "/js/games/highlow/images/flags/morocco.jpg" },
            { name: "Uzbekistan", value: 36000000, desc: "Central Asia", img: "/js/games/highlow/images/flags/uzbekistan.jpg" },
            { name: "Peru", value: 34000000, desc: "South America", img: "/js/games/highlow/images/flags/peru.jpg" },
            { name: "Malaysia", value: 34000000, desc: "Asia", img: "/js/games/highlow/images/flags/malaysia.jpg" },
            { name: "Saudi Arabia", value: 36000000, desc: "Middle East", img: "/js/games/highlow/images/flags/saudi_arabia.jpg" },
            { name: "Venezuela", value: 28000000, desc: "South America", img: "/js/games/highlow/images/flags/venezuela.jpg" },
            { name: "Chile", value: 19000000, desc: "South America", img: "/js/games/highlow/images/flags/chile.jpg" },
            { name: "Romania", value: 19000000, desc: "Europe", img: "/js/games/highlow/images/flags/romania.jpg" },
            { name: "Ecuador", value: 18000000, desc: "South America", img: "/js/games/highlow/images/flags/ecuador.jpg" },
            { name: "Guatemala", value: 18000000, desc: "Central America", img: "/js/games/highlow/images/flags/guatemala.jpg" },
            { name: "Belgium", value: 11000000, desc: "Europe", img: "/js/games/highlow/images/flags/belgium.jpg" },
            { name: "Sweden", value: 10500000, desc: "Europe", img: "/js/games/highlow/images/flags/sweden.jpg" },
            { name: "Portugal", value: 10300000, desc: "Europe", img: "/js/games/highlow/images/flags/portugal.jpg" },
            { name: "Greece", value: 10400000, desc: "Europe", img: "/js/games/highlow/images/flags/greece.jpg" },
            { name: "Austria", value: 9000000, desc: "Europe", img: "/js/games/highlow/images/flags/austria.jpg" }
        ]
        
    },

    movies: {
        title: "MOVIES",
        subtitle: "IMDb RATING",
        color: "#f5c518",
        items: [
            { name: "Avatar", value: 7.9, desc: "2009", img: "/js/games/highlow/images/movies/avatar.jpg" },
            { name: "Titanic", value: 7.9, desc: "1997", img: "/js/games/highlow/images/movies/titanic.jpg" },
            { name: "Avengers: Endgame", value: 8.4, desc: "2019", img: "/js/games/highlow/images/movies/endgame.jpg" },
            { name: "The Dark Knight", value: 9.0, desc: "2008", img: "/js/games/highlow/images/movies/dark_knight.jpg" },
            { name: "Inception", value: 8.8, desc: "2010", img: "/js/games/highlow/images/movies/inception.jpg" },
            { name: "Interstellar", value: 8.7, desc: "2014", img: "/js/games/highlow/images/movies/interstellar.jpg" },
            { name: "The Matrix", value: 8.7, desc: "1999", img: "/js/games/highlow/images/movies/matrix.jpg" },
            { name: "Harry Potter 1", value: 7.6, desc: "2001", img: "/js/games/highlow/images/movies/hp1.jpg" },
            { name: "The Lion King", value: 8.5, desc: "1994", img: "/js/games/highlow/images/movies/lion_king.jpg" },
            { name: "Forrest Gump", value: 8.8, desc: "1994", img: "/js/games/highlow/images/movies/forrest_gump.jpg" },
            { name: "Spider-Man: No Way Home", value: 8.2, desc: "2021", img: "/js/games/highlow/images/movies/spiderman_nwh.jpg" },
            { name: "Joker", value: 8.4, desc: "2019", img: "/js/games/highlow/images/movies/joker.jpg" },
            { name: "Deadpool", value: 8.0, desc: "2016", img: "/js/games/highlow/images/movies/deadpool.jpg" },
            { name: "Iron Man", value: 7.9, desc: "2008", img: "/js/games/highlow/images/movies/iron_man.jpg" },
            { name: "Pirates of the Caribbean", value: 8.1, desc: "2003", img: "/js/games/highlow/images/movies/pirates.jpg" },
            { name: "The Lord of the Rings 1", value: 8.9, desc: "2001", img: "/js/games/highlow/images/movies/lotr1.jpg" },
            { name: "Oppenheimer", value: 8.3, desc: "2023", img: "/js/games/highlow/images/movies/oppenheimer.jpg" },
            { name: "Barbie", value: 6.9, desc: "2023", img: "/js/games/highlow/images/movies/barbie.jpg" },
            { name: "Dune: Part Two", value: 8.6, desc: "2024", img: "/js/games/highlow/images/movies/dune2.jpg" },
            { name: "The Wolf of Wall Street", value: 8.2, desc: "2013", img: "/js/games/highlow/images/movies/wolf.jpg" },
            { name: "Gladiator", value: 8.5, desc: "2000", img: "/js/games/highlow/images/movies/gladiator.jpg" },
            { name: "Shrek", value: 7.9, desc: "2001", img: "/js/games/highlow/images/movies/shrek.jpg" },
            { name: "John Wick", value: 7.4, desc: "2014", img: "/js/games/highlow/images/movies/john_wick.jpg" },
            { name: "Star Wars: Ep. IV", value: 8.6, desc: "1977", img: "/js/games/highlow/images/movies/star_wars.jpg" },
            { name: "Pulp Fiction", value: 8.9, desc: "1994", img: "/js/games/highlow/images/movies/pulp_fiction.jpg" },
            { name: "The Godfather", value: 9.2, desc: "1972", img: "/js/games/highlow/images/movies/godfather.jpg" },
            { name: "The Green Mile", value: 8.6, desc: "1999", img: "/js/games/highlow/images/movies/green_mile.jpg" },
            { name: "Parasite", value: 8.5, desc: "2019", img: "/js/games/highlow/images/movies/parasite.jpg" },
            { name: "The Silence of the Lambs", value: 8.6, desc: "1991", img: "/js/games/highlow/images/movies/lambs.jpg" },
            { name: "Saving Private Ryan", value: 8.6, desc: "1998", img: "/js/games/highlow/images/movies/ryan.jpg" },
            { name: "Seven", value: 8.6, desc: "1995", img: "/js/games/highlow/images/movies/se7en.jpg" },
            { name: "Back to the Future", value: 8.5, desc: "1985", img: "/js/games/highlow/images/movies/bttf.jpg" },
            { name: "Whiplash", value: 8.5, desc: "2014", img: "/js/games/highlow/images/movies/whiplash.jpg" },
            { name: "The Prestige", value: 8.5, desc: "2006", img: "/js/games/highlow/images/movies/prestige.jpg" },
            { name: "The Departed", value: 8.5, desc: "2006", img: "/js/games/highlow/images/movies/departed.jpg" },
            { name: "Spider-Man: Across the Spider-Verse", value: 8.6, desc: "2023", img: "/js/games/highlow/images/movies/spiderverse.jpg" },
            { name: "Top Gun: Maverick", value: 8.2, desc: "2022", img: "/js/games/highlow/images/movies/maverick.jpg" },
            { name: "The Dark Knight Rises", value: 8.4, desc: "2012", img: "/js/games/highlow/images/movies/dk_rises.jpg" },
            { name: "Django Unchained", value: 8.5, desc: "2012", img: "/js/games/highlow/images/movies/django.jpg" },
            { name: "Coco", value: 8.4, desc: "2017", img: "/js/games/highlow/images/movies/coco.jpg" },
            { name: "WALL-E", value: 8.4, desc: "2008", img: "/js/games/highlow/images/movies/walle.jpg" },
            { name: "Inglourious Basterds", value: 8.3, desc: "2009", img: "/js/games/highlow/images/movies/basterds.jpg" },
            { name: "Toy Story", value: 8.3, desc: "1995", img: "/js/games/highlow/images/movies/toy_story.jpg" },
            { name: "Logan", value: 8.1, desc: "2017", img: "/js/games/highlow/images/movies/logan.jpg" },
            { name: "Mad Max: Fury Road", value: 8.1, desc: "2015", img: "/js/games/highlow/images/movies/mad_max.jpg" },
            { name: "Jurassic Park", value: 8.2, desc: "1993", img: "/js/games/highlow/images/movies/jurassic.jpg" },
            { name: "The Truman Show", value: 8.2, desc: "1998", img: "/js/games/highlow/images/movies/truman.jpg" }
        ]
    },

    brands: {
        title: "BRAND",
        subtitle: "MARKET CAP (TRILLIONS $)",
        color: "#00f2ff", // Яркий неоновый голубой (киберпанк стиль)
        items: [
            // --- ТИТАНЫ (3.0+ TRILLION) ---
            { name: "Microsoft", value: 3.4, desc: "Software & AI", img: "/js/games/highlow/images/brands/microsoft.jpg" },
            { name: "Apple", value: 3.3, desc: "Consumer Tech", img: "/js/games/highlow/images/brands/apple.jpg" },
            { name: "NVIDIA", value: 3.2, desc: "AI & GPU Chips", img: "/js/games/highlow/images/brands/nvidia.jpg" },

            // --- МАГНАТЫ (1.0 - 2.5 TRILLION) ---
            { name: "Alphabet (Google)", value: 2.1, desc: "Search & Advertising", img: "/js/games/highlow/images/brands/google.jpg" },
            { name: "Amazon", value: 1.9, desc: "E-commerce & Cloud", img: "/js/games/highlow/images/brands/amazon.jpg" },
            { name: "Meta (Facebook)", value: 1.2, desc: "Social Media", img: "/js/games/highlow/images/brands/meta.jpg" },

            // --- КРУПНЫЕ ИЗВЕСТНЫЕ БРЕНДЫ (0.3 - 0.9 TRILLION) ---
            { name: "Tesla", value: 0.8, desc: "Electric Vehicles", img: "/js/games/highlow/images/brands/tesla.jpg" },
            { name: "Visa", value: 0.6, desc: "Financial Services", img: "/js/games/highlow/images/brands/visa.jpg" },
            { name: "Walmart", value: 0.5, desc: "Retail Giant", img: "/js/games/highlow/images/brands/walmart.jpg" },
            { name: "LVMH (Louis Vuitton)", value: 0.4, desc: "Luxury Goods", img: "/js/games/highlow/images/brands/lvmh.jpg" },
            { name: "Samsung", value: 0.4, desc: "Electronics", img: "/js/games/highlow/images/brands/samsung.jpg" },

            // --- ИЗВЕСТНЫЕ, НО "ДЕШЕВЛЕ" (0.1 - 0.2 TRILLION) ---
            { name: "Coca-Cola", value: 0.2, desc: "Beverages", img: "/js/games/highlow/images/brands/cocacola.jpg" },
            { name: "Toyota", value: 0.2, desc: "Automotive", img: "/js/games/highlow/images/brands/toyota.jpg" },
            { name: "Netflix", value: 0.2, desc: "Streaming Service", img: "/js/games/highlow/images/brands/netflix.jpg" },
            { name: "McDonald's", value: 0.2, desc: "Fast Food", img: "/js/games/highlow/images/brands/mcdonalds.jpg" },
            { name: "Disney", value: 0.1, desc: "Entertainment", img: "/js/games/highlow/images/brands/disney.jpg" },
            { name: "Nike", value: 0.1, desc: "Sportswear", img: "/js/games/highlow/images/brands/nike.jpg" },
            { name: "Intel", value: 0.1, desc: "Processors", img: "/js/games/highlow/images/brands/intel.jpg" },
            { name: "Sony", value: 0.1, desc: "Gaming & Music", img: "/js/games/highlow/images/brands/sony.jpg" },
            { name: "Ferrari", value: 0.08, desc: "Luxury Cars", img: "/js/games/highlow/images/brands/ferrari.jpg" },
            { name: "Spotify", value: 0.06, desc: "Music Streaming", img: "/js/games/highlow/images/brands/spotify.jpg" },

            // --- ТЕХНОЛОГИЧЕСКИЕ ГИГАНТЫ (ВТОРОЙ ЭШЕЛОН) ---
            { name: "Oracle", value: 0.46, desc: "Cloud & Software", img: "/js/games/highlow/images/brands/oracle.jpg" },
            { name: "IBM", value: 0.19, desc: "AI & Computing", img: "/js/games/highlow/images/brands/ibm.jpg" },
            { name: "Uber", value: 0.16, desc: "Ride-hailing", img: "/js/games/highlow/images/brands/uber.jpg" },

            // --- БРЕНДЫ ДЛЯ ЛОВУШЕК (ВЫГЛЯДЯТ ДОРОЖЕ, ЧЕМ ЕСТЬ) ---
            { name: "Porsche", value: 0.08, desc: "Luxury Sports Cars", img: "/js/games/highlow/images/brands/porsche.jpg" },
            { name: "Mercedes-Benz", value: 0.07, desc: "Automotive", img: "/js/games/highlow/images/brands/mercedes.jpg" },
            { name: "BMW", value: 0.06, desc: "Automotive", img: "/js/games/highlow/images/brands/bmw.jpg" },
            { name: "Starbucks", value: 0.11, desc: "Coffee Chain", img: "/js/games/highlow/images/brands/starbucks.jpg" },
            { name: "Airbnb", value: 0.09, desc: "Travel & Rent", img: "/js/games/highlow/images/brands/airbnb.jpg" },

            // --- ГЕЙМИНГ (ОЧЕНЬ АЗАРТНО СРАВНИВАТЬ) ---
            { name: "EA (Electronic Arts)", value: 0.04, desc: "FIFA & Games", img: "/js/games/highlow/images/brands/ea.jpg" },
            { name: "Roblox", value: 0.03, desc: "Gaming Platform", img: "/js/games/highlow/images/brands/roblox.jpg" },

            // --- ОДЕЖДА И ФЕШН ---
            { name: "Hermès", value: 0.24, desc: "Luxury Fashion", img: "/js/games/highlow/images/brands/hermes.jpg" },
            { name: "Dior", value: 0.14, desc: "Luxury Fashion", img: "/js/games/highlow/images/brands/dior.jpg" },
            { name: "Adidas", value: 0.04, desc: "Sportswear", img: "/js/games/highlow/images/brands/adidas.jpg" },
            { name: "Puma", value: 0.007, desc: "Sportswear", img: "/js/games/highlow/images/brands/puma.jpg" },

            // --- РАЗНОЕ ---
            { name: "PepsiCo", value: 0.23, desc: "Food & Drinks", img: "/js/games/highlow/images/brands/pepsi.jpg" },
            { name: "Mastercard", value: 0.44, desc: "Payments", img: "/js/games/highlow/images/brands/mastercard.jpg" }
        ]
    }

};